# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class DEVICE_COMMAND(object):
    WRITE = 0
    READ = 1
    ALL_TENSIX_RESET_DEASSERT = 2
    ALL_TENSIX_RESET_ASSERT = 3
    START = 4
    EXIT = 5
