# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class tt_vcs_core(object):
    __slots__ = ["_tab"]

    # tt_vcs_core
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # tt_vcs_core
    def X(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint64Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0),
        )

    # tt_vcs_core
    def Y(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint64Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8),
        )


def Creatett_vcs_core(builder, x, y):
    builder.Prep(8, 16)
    builder.PrependUint64(y)
    builder.PrependUint64(x)
    return builder.Offset()
