# automatically generated by the FlatBuffers compiler, do not modify
# (import of tt_vcs_core patched to be relative — see server/regen_flatbuf.sh)

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class DeviceRequestResponse(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsDeviceRequestResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeviceRequestResponse()
        x.Init(buf, n + offset)
        return x

    # DeviceRequestResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeviceRequestResponse
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # DeviceRequestResponse
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # DeviceRequestResponse
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # DeviceRequestResponse
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DeviceRequestResponse
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # DeviceRequestResponse
    def Core(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .tt_vcs_core import tt_vcs_core

            obj = tt_vcs_core()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DeviceRequestResponse
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DeviceRequestResponse
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0


def DeviceRequestResponseStart(builder):
    builder.StartObject(5)


def DeviceRequestResponseAddCommand(builder, command):
    builder.PrependInt8Slot(0, command, 0)


def DeviceRequestResponseAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0
    )


def DeviceRequestResponseStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def DeviceRequestResponseAddCore(builder, core):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(core), 0)


def DeviceRequestResponseAddAddress(builder, address):
    builder.PrependUint64Slot(3, address, 0)


def DeviceRequestResponseAddSize(builder, size):
    builder.PrependUint32Slot(4, size, 0)


def DeviceRequestResponseEnd(builder):
    return builder.EndObject()
